# gitprompt shell integration — generated by "gitprompt init bash"
# Add to ~/.bashrc: eval "$($HOME/.local/bin/gitprompt.exe init bash)"
if [[ "$OSTYPE" == msys || "$OSTYPE" == cygwin ]]; then
  _GITPROMPT_BIN="$HOME/.local/bin/gitprompt.exe"
  _GITPROMPT_FALLBACK_PS1='\w > '
else
  _GITPROMPT_BIN="$HOME/.local/bin/gitprompt"
  _GITPROMPT_FALLBACK_PS1='\w \$ '
fi

gitprompt() {
  "$_GITPROMPT_BIN" "$@"
}

if [ -z "${_GITPROMPT_ORIGINAL_PS1+x}" ]; then
  _GITPROMPT_ORIGINAL_PS1="$PS1"
fi

__gitprompt_preexec_flag=0
__gitprompt_running=0
__gitprompt_cmd_start_us=""

__gitprompt_debug_trap() {
  if [ "$__gitprompt_running" -eq 0 ] && [ "$BASH_COMMAND" != "_gitprompt_update_ps1" ]; then
    if [ "$__gitprompt_preexec_flag" -eq 0 ] && [ -n "${EPOCHREALTIME+x}" ]; then
      __gitprompt_cmd_start_us=${EPOCHREALTIME/./}
    fi
    __gitprompt_preexec_flag=1
  fi
}

__gitprompt_prompt_sp() {
  [ -t 1 ] || return
  local pos _d
  while IFS= read -d R -rs -t 0.02 _d 2>/dev/null; do :; done
  printf '\e[6n' >&1
  IFS='[;' read -d R -a pos -rs -t 0.3 2>/dev/null || return
  local col="${pos[2]:-1}"
  [ "${col}" -gt 1 ] && printf '\n'
}

_gitprompt_update_ps1() {
  __gitprompt_running=1
  local _last_cmd_ms=""
  if [ -n "$__gitprompt_cmd_start_us" ]; then
    local _end_us=${EPOCHREALTIME/./}
    _last_cmd_ms=$(( (_end_us - __gitprompt_cmd_start_us) / 1000 ))
    __gitprompt_cmd_start_us=""
  elif [ -n "${EPOCHREALTIME+x}" ]; then
    _last_cmd_ms="0"
  fi
  __gitprompt_prompt_sp
  if [ "$__gitprompt_preexec_flag" -eq 1 ]; then
    __gitprompt_preexec_flag=0
    "$_GITPROMPT_BIN" --invalidate-status-cache >/dev/null 2>&1 || true
  fi
  if output="$(GITPROMPT_LAST_CMD_MS="$_last_cmd_ms" "$_GITPROMPT_BIN" 2>/dev/null)" && [ -n "$output" ]; then
    PS1="$output"
  else
    PS1="${_GITPROMPT_ORIGINAL_PS1:-$_GITPROMPT_FALLBACK_PS1}"
  fi
  __gitprompt_running=0
}

if [ -x "$_GITPROMPT_BIN" ]; then
  trap '__gitprompt_debug_trap' DEBUG
  PROMPT_COMMAND="_gitprompt_update_ps1${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
fi

_gitprompt_complete() {
  [ "$COMP_CWORD" -eq 0 ] && return
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
    gitprompt|gitprompt.exe) COMPREPLY=($(compgen -W "{{GITPROMPT_COMMANDS}}" -- "$cur")) ;;
    init)                    COMPREPLY=($(compgen -W "bash" -- "$cur")) ;;
    config)                  COMPREPLY=($(compgen -W "reset" -- "$cur")) ;;
  esac
}
complete -F _gitprompt_complete gitprompt
[[ "$OSTYPE" == msys || "$OSTYPE" == cygwin ]] && complete -F _gitprompt_complete gitprompt.exe

_gitprompt_aliases="$HOME/.local/share/gitprompt/git_aliases.sh"
# shellcheck disable=SC1090
[ -f "$_gitprompt_aliases" ] && . "$_gitprompt_aliases"
unset _gitprompt_aliases
