# gitprompt shell integration — generated by "gitprompt init bash"
# Add to ~/.bashrc: eval "$($HOME/.local/bin/gitprompt.exe init bash)"
if [[ "$OSTYPE" == msys || "$OSTYPE" == cygwin ]]; then
  _GITPROMPT_BIN="$HOME/.local/bin/gitprompt.exe"
else
  _GITPROMPT_BIN="$HOME/.local/bin/gitprompt"
fi

__gitprompt_preexec_flag=0
__gitprompt_running=0

__gitprompt_debug_trap() {
  if [ "$__gitprompt_running" -eq 0 ] && [ "$BASH_COMMAND" != "_gitprompt_update_ps1" ]; then
    __gitprompt_preexec_flag=1
  fi
}

_gitprompt_update_ps1() {
  __gitprompt_running=1
  if [ "$__gitprompt_preexec_flag" -eq 1 ]; then
    __gitprompt_preexec_flag=0
    "$_GITPROMPT_BIN" --invalidate-status-cache >/dev/null 2>&1 || true
  fi
  if output="$("$_GITPROMPT_BIN" 2>/dev/null)" && [ -n "$output" ]; then
    PS1="$output"
  else
    PS1='__FALLBACK_PS1__'
  fi
  __gitprompt_running=0
}

if [ -x "$_GITPROMPT_BIN" ]; then
  trap '__gitprompt_debug_trap' DEBUG
  PROMPT_COMMAND="_gitprompt_update_ps1${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
fi

if [[ "$OSTYPE" == msys || "$OSTYPE" == cygwin ]]; then
  gitprompt() { "$_GITPROMPT_BIN" "$@"; }
fi

_gitprompt_complete() {
  [ "$COMP_CWORD" -eq 0 ] && return
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
    gitprompt|gitprompt.exe) COMPREPLY=($(compgen -W "init config update uninstall --help" -- "$cur")) ;;
    init)                    COMPREPLY=($(compgen -W "bash" -- "$cur")) ;;
  esac
}
complete -F _gitprompt_complete gitprompt
[[ "$OSTYPE" == msys || "$OSTYPE" == cygwin ]] && complete -F _gitprompt_complete gitprompt.exe
